# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: testCSO

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      app:
        description: 'App Name (jag-role-registry)'    
        required: true
        default: jag-role-registry
      env:
        type: choice
        description: Image Target environment
        options: 
        - dev    
        required: true
        default: 'dev'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:    
    - name: Run Integration Tests
      env:
        TEST_STARTER_URL: ${{secrets.TEST_STARTER_URL}}
        BASIC_AUTH_USER: ${{secrets.BASIC_AUTH_USER}}
        BASIC_AUTH_PASS: ${{secrets.BASIC_AUTH_PASS}}
      run: |
        RET=`curl --write-out '%{content_type}' --output TestErrors.zip --request GET --user ${BASIC_AUTH_USER}:${BASIC_AUTH_PASS} --url ${TEST_STARTER_URL}`
        if [ "$RET" = "application/zip" ]; then
          echo "Status: Failed Integration Test(s) found!"
          exit 1
        fi
        if [[ "$RET" == *"json"* ]]; then
          echo "Status: All Tests Passed"
        fi
        if [ "$RET" != "application/zip" ] && [[ "$RET" != *"json"* ]]; then
          echo "Received content_type is $RET, was expecting json or zip"
          exit 1
        fi  
    - name: Run Integration Tests        
      uses: actions/upload-artifact@v3.1.1
      if: failure()
      with:
        name: integration-tests-report
        path: |
          TestErrors.zip
        retention-days: 5     
          
