# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: testCSO

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run:  echo ${{secrets.TEST_STARTER_URL}} | sed 's/./& /g'      
    - name: Run Integration Tests
      run: |
        RET=`curl --write-out '%{content_type}' --output TestErrors.zip --request GET --user csodev:Welcome12! --url "https://jag-role-registry-tests-e97df9-dev.apps.gold.devops.gov.bc.ca/tests/all"`
        if [ "$RET" = "application/zip" ]; then
          echo "Status: Failed Integration Test(s) found!"
          exit 1
        fi
        if [[ "$RET" == *"json"* ]]; then
          echo "Status: All Tests Passed"
        fi
        if [ "$RET" != "application/zip" ] && [[ "$RET" != *"json"* ]]; then
          echo "Received content_type is $RET, was expecting json or zip"
          exit 1
        fi  
    - name: Run Integration Tests        
      uses: actions/upload-artifact@v3.1.1
      if: failure()
      with:
        name: integration-tests-report
        path: |
          TestErrors.zip
        retention-days: 5     
          
